export default {
  "text.accept": "确定",
  "text.aspect-ratio": "纵横比",
  "text.back": "后退",
  "text.b": "B",
  "text.bold": "加粗",
  "text.breadcrumb": "面包屑",
  "text.bullets": "项目符号",
  "text.c": "C#",
  "text.camera-api-is-not-available-in-this-browser": "此浏览器不支持摄像头 API。",
  "text.camera-permission-was-denied": "摄像头权限被拒绝。",
  "text.captured": "已捕获：",
  "text.cast": "投放",
  "text.clear-formatting": "清除格式",
  "text.clear-text": "清除文本",
  "text.close": "关闭",
  "text.close-overflow-menu": "关闭溢出菜单",
  "text.command-bar": "命令栏",
  "text.copy": "复制",
  "text.cut": "剪切",
  "text.g": "G",
  "text.hue": "色相",
  "text.integrated-camera": "内置摄像头",
  "text.italic": "斜体",
  "text.more": "更多",
  "text.more-options": "更多选项",
  "text.mute": "静音",
  "text.navigation-menu": "导航菜单",
  "text.open-navigation": "打开导航",
  "text.close-navigation": "关闭导航",
  "text.next": "下一项",
  "text.navigationview": "导航视图",
  "text.navigationview-description": "NavigationView 控件通过可折叠导航菜单，为应用的顶级区域提供通用的垂直布局。",
  "sample.navigationview.default-header": "使用默认 PaneDisplayMode 的 NavigationView",
  "sample.navigationview.top-header": "将 PaneDisplayMode 设置为 Top 的 NavigationView",
  "sample.navigationview.adaptive-header": "根据窗口宽度切换窗格方向的 NavigationView",
  "sample.navigationview.tabs-header": "关联选择与焦点 - 选项卡",
  "sample.navigationview.data-binding-header": "数据绑定",
  "sample.navigationview.footer-header": "带页脚菜单项的 NavigationView",
  "sample.navigationview.hierarchical-header": "层级 NavigationView",
  "sample.navigationview.api-header": "API 实际应用",
  "sample.navigationview.default-description": "如果有五个或更多同等重要的导航类别，且这些类别应在较大的窗口宽度下突出显示，请考虑使用左侧导航窗格。",
  "sample.navigationview.top-description": "如果有同等重要的导航类别，但相对于应用内容应弱化显示，请考虑使用顶部导航窗格。",
  "sample.navigationview.adaptive-description": "如果导航类别同等重要且应用内容空间有限，请考虑在较大的窗口宽度下使用顶部导航窗格，在较小的窗口宽度下使用最小化左侧导航窗格。",
  "sample.navigationview.tabs-description": "对于选项卡模式，请将 SelectionFollowsFocus 属性设置为 Enabled，使选择与焦点保持一致。如果使用 Frame 切换内容，则不应将项目之间的导航记录到 Frame 的导航堆栈中。请参阅下方示例中的 C# 代码了解具体做法。",
  "sample.navigationview.data-binding-description": "进行数据绑定时，请使用 MenuItemsSource 属性绑定可观察的项目集合，并且不要设置 MenuItems 属性。此外，请设置 MenuItemTemplate 属性并使用 NavigationViewItem 作为数据模板。如果还希望绑定标题内容，请通过 MenuItemTemplateSelector 属性使用数据模板选择器。",
  "sample.navigationview.footer-description": "可以向 NavigationView 的页脚添加可点击菜单项，这些项目与主菜单项目使用相同的选择模型。在 Top PaneDisplayMode 中，这些项目会在 NavigationView 右侧对齐；在 Left PaneDisplayMode 中，这些项目会在 NavigationView 底部对齐。",
  "sample.navigationview.hierarchy-description-1": "NavigationView 在 Left、LeftCompact 和 Top 显示模式中支持层级结构。",
  "sample.navigationview.hierarchy-description-2": "在下面的示例中，“帐户”选项卡会导航到自己的页面，而“文档选项”只会展开其子项目。实现方式是将“文档选项”NavigationView 项的 SelectsOnInvoked 属性设置为 false。",
  "sample.navigationview.hierarchy-description-3": "在 Top 和 Left 模式中，点击 NavigationViewItem 上的箭头会展开或折叠子树。点击或轻触 NavigationViewItem 的其他位置也会折叠或展开子树。",
  "sample.navigationview.hierarchy-description-4": "请在右侧切换三种窗格显示模式。",
  "sample.navigationview.header-text": "这是标题文本",
  "sample.navigationview.menu-item-1": "菜单项 1",
  "sample.navigationview.menu-item-2": "菜单项 2",
  "sample.navigationview.menu-item-3": "菜单项 3",
  "sample.navigationview.menu-item-4": "菜单项 4",
  "sample.navigationview.item-1": "项目 1",
  "sample.navigationview.item-2": "项目 2",
  "sample.navigationview.item-3": "项目 3",
  "sample.navigationview.item-4": "项目 4",
  "sample.navigationview.sample-page": "示例页面 {number}",
  "sample.navigationview.settings-page": "示例设置页",
  "sample.navigationview.lorem-title": "这是示例页面的标题内容",
  "sample.navigationview.lorem-body": "这是用于展示页面布局的示例正文。它用于说明内容在不同窗口宽度和导航窗格状态下如何排列、换行与滚动，并确保页面底部内容始终可以完整查看。",
  "sample.navigationview.category": "类别 {number}",
  "sample.navigationview.category-tooltip": "这是类别 {number}",
  "sample.navigationview.browse": "浏览",
  "sample.navigationview.track-order": "跟踪订单",
  "sample.navigationview.order-history": "订单历史记录",
  "sample.navigationview.account": "帐户",
  "sample.navigationview.your-cart": "购物车",
  "sample.navigationview.help": "帮助",
  "sample.navigationview.pane-position": "窗格位置：",
  "sample.navigationview.pane-position-property": "窗格位置：",
  "sample.navigationview.left-mode": "Left 模式",
  "sample.navigationview.top-mode": "Top 模式",
  "sample.navigationview.left-compact-mode": "LeftCompact 模式",
  "sample.navigationview.home": "主页",
  "sample.navigationview.mail": "邮件",
  "sample.navigationview.calendar": "日历",
  "sample.navigationview.document-options": "文档选项",
  "sample.navigationview.create-new": "新建",
  "sample.navigationview.upload-file": "上传文件",
  "sample.navigationview.settings-visible": "显示设置项",
  "sample.navigationview.back-visible": "显示后退按钮",
  "sample.navigationview.back-enabled": "启用后退按钮",
  "sample.navigationview.autosuggest-visible": "显示 AutoSuggestBox",
  "sample.navigationview.header-label": "Header：",
  "sample.navigationview.header-value": "标题",
  "sample.navigationview.always-show-header": "始终显示标题",
  "sample.navigationview.pane-title-label": "PaneTitle：",
  "sample.navigationview.pane-title-value": "窗格标题",
  "sample.navigationview.pane-custom-visible": "显示 PaneCustomContent",
  "sample.navigationview.pane-footer-visible": "显示 PaneFooter",
  "sample.navigationview.left": "Left",
  "sample.navigationview.top": "Top",
  "sample.navigationview.keyboard-selection-follows-focus": "键盘 SelectionFollowsFocus",
  "sample.navigationview.suppress-menu-item-2": "禁止选择菜单项 2",
  "sample.navigationview.actions": "操作",
  "sample.navigationview.more-info": "更多信息",
  "sample.navigationview.search": "搜索",
  "sample.navigationview.download": "下载",
  "sample.navigationview.favorite": "收藏",
  "sample.navigationview.change-theme": "切换主题",
  "sample.navigationview.add-favorite": "添加到收藏",
  "sample.navigationview.remove-favorite": "从收藏中移除",
  "text.numbering": "编号",
  "text.off": "关",
  "text.on": "开",
  "sample.opacity": "不透明度",
  "text.paste": "粘贴",
  "text.pause": "暂停",
  "text.play": "播放",
  "text.previous": "上一项",
  "text.r": "R",
  "text.redo": "重做",
  "text.requesting-camera-permission": "正在请求摄像头权限...",
  "text.reveal-password": "显示密码",
  "text.scroll-left": "向左滚动",
  "text.scroll-right": "向右滚动",
  "text.search": "搜索",
  "text.select": "选择...",
  "text.select-all": "全选",
  "text.settings": "设置",
  "text.source-code": "源代码",
  "text.saturation": "饱和度",
  "text.submit-query": "提交查询",
  "text.switch-to-zoomed-out-view": "切换到缩小视图",
  "text.cancel": "取消",
  "text.unable-to-start-the-camera": "无法启动摄像头。",
  "text.underline": "下划线",
  "text.undo": "撤消",
  "text.unmute": "取消静音",
  "text.value": "明度",
  "text.volume": "音量",
  "text.vue": "Vue",
  "text.xaml": "XAML",
  "control.infobadge.value": "{value} 条通知",
  "control.infobadge.icon": "通知",
  "control.infobadge.dot": "新通知",
  "control.infobar.close-button-name": "关闭",
  "control.infobar.close-button-tooltip": "关闭"
};
