export default {
  "app.shortTitle": "VoiceCraft",
  "app.title": "VoiceCraft",
  "app.version": "1.0.0",
  "app.author": "VoiceCraft",
  "text.app-name": "VoiceCraft",
  "text.app-description": "AI 驱动的文字转语音平台，基于微软 Edge TTS。",
  "text.tts": "文字转语音",
  "text.file-tts": "文件配音",
  "text.file-description": "上传 txt 文本文件批量生成语音。",
  "text.nav-text": "文本配音",
  "text.nav-file": "文件配音",
  "text.input-text": "输入文本",
  "text.input-placeholder": "请输入要转换为语音的文本内容，支持中文、英文、数字等...",
  "text.upload-txt": "上传 txt 文件",
  "text.voice": "语音角色",
  "text.speed": "语速调节",
  "text.pitch": "音调高低",
  "text.style": "语音风格",
  "text.generate": "开始生成语音",
  "text.generating": "生成中...",
  "text.loading": "正在生成语音，请稍候...",
  "text.download": "下载音频文件",
  "text.clear": "清空结果",
  "text.error-empty": "请输入要转换的文本内容",
  "text.error-file-type": "请选择txt格式的文本文件",
  "text.error-file-size": "文件大小不能超过500KB",
  "text.error-file-empty": "请选择要上传的txt文件",
  "text.success": "生成成功",
  "text.error-failed": "生成失败",
  "text.processing-file": "正在处理上传的文件...",
  "text.processing-long": "正在处理长文本，请耐心等待...",
  "text.upload-hint": "支持txt格式，最大500KB",
  "text.tab-text": "手动输入",
  "text.tab-file": "上传文件",
  "text.settings": "设置",
  "text.settings-description": "调整默认配音参数，文本与文件配音均会使用这些默认值。",
  "text.settings-hint": "修改后自动保存，并应用于后续的语音生成。",
  "text.settings-section-tts": "配音设置",
  "text.voice-description": "选择默认语音角色",
  "text.speed-description": "选择默认语速",
  "text.pitch-description": "选择默认音调",
  "text.style-description": "选择默认语音风格",
  "text.about": "关于",
  "text.about-copyright": "© {year} {name} · 版本 {version} · {author}",
  "text.about-opensource": "开源与引用",
  "text.about-project-1": "wangwangit/tts — Edge TTS 服务端逻辑",
  "text.about-project-2": "Furry-Xiyi/WinUIonWeb — WinUI 风格前端组件库",
  "text.about-project-3": "VoiceCraftWorker",
  "text.about-license-mit": "(MIT License)",
  "text.about-license-gpl": "(GPL-3.0 License)",
  "text.about-license-notice": "本项目基于 GPL-3.0 许可证发布。同时引用了其它开源项目的代码，其版权归原作者所有，遵循各自许可证条款。"
};