export default {
  "app.shortTitle": "VoiceCraft",
  "app.title": "VoiceCraft",
  "app.version": "1.0.0",
  "app.author": "VoiceCraft",
  "text.app-name": "VoiceCraft",
  "text.app-description": "AI text-to-speech platform powered by Microsoft Edge TTS.",
  "text.tts": "Text to Speech",
  "text.file-tts": "File Dubbing",
  "text.file-description": "Upload a txt file to generate speech in batch.",
  "text.nav-text": "Text Dubbing",
  "text.nav-file": "File Dubbing",
  "text.input-text": "Input text",
  "text.input-placeholder": "Enter the text to convert to speech...",
  "text.upload-txt": "Upload txt file",
  "text.voice": "Voice",
  "text.speed": "Speed",
  "text.pitch": "Pitch",
  "text.style": "Style",
  "text.generate": "Generate speech",
  "text.generating": "Generating...",
  "text.loading": "Generating speech, please wait...",
  "text.download": "Download audio",
  "text.error-empty": "Please enter the text to convert",
  "text.error-file-type": "Please select a txt text file",
  "text.error-file-size": "File size cannot exceed 500KB",
  "text.error-file-empty": "Please select a txt file to upload",
  "text.success": "Speech generated",
  "text.error-failed": "Generation failed",
  "text.processing-file": "Processing uploaded file...",
  "text.processing-long": "Processing long text, please wait...",
  "text.upload-hint": "txt only, up to 500KB",
  "text.tab-text": "Manual input",
  "text.tab-file": "Upload file",
  "text.settings": "Settings",
  "text.settings-description": "Adjust default dubbing parameters. Both text and file dubbing use these defaults.",
  "text.settings-hint": "Changes are saved automatically and applied to subsequent generations.",
  "text.settings-section-tts": "Dubbing Settings",
  "text.voice-description": "Select the default voice",
  "text.speed-description": "Select the default speed",
  "text.pitch-description": "Select the default pitch",
  "text.style-description": "Select the default style",
  "text.about": "About",
  "text.about-copyright": "© {year} {name} · Version {version} · {author}",
  "text.about-opensource": "Open Source & Credits",
  "text.about-project-1": "wangwangit/tts — Edge TTS server logic",
  "text.about-project-2": "Furry-Xiyi/WinUIonWeb — WinUI-style frontend component library",
  "text.about-project-3": "VoiceCraftWorker",
  "text.about-license-mit": "(MIT License)",
  "text.about-license-gpl": "(GPL-3.0 License)",
  "text.about-license-notice": "This project is released under the GPL-3.0 license. It also references code from other open-source projects, whose copyright belongs to their respective authors and follow their own license terms."
};