export default {
  "text.accept": "Accept",
  "text.aspect-ratio": "Aspect ratio",
  "text.back": "Back",
  "text.b": "B",
  "text.bold": "Bold",
  "text.breadcrumb": "Breadcrumb",
  "text.bullets": "Bullets",
  "text.c": "C#",
  "text.camera-api-is-not-available-in-this-browser": "Camera API is not available in this browser.",
  "text.camera-permission-was-denied": "Camera permission was denied.",
  "text.captured": "Captured:",
  "text.cast": "Cast",
  "text.clear-formatting": "Clear formatting",
  "text.clear-text": "Clear text",
  "text.close": "Close",
  "text.close-overflow-menu": "Close overflow menu",
  "text.command-bar": "Command bar",
  "text.copy": "Copy",
  "text.cut": "Cut",
  "text.g": "G",
  "text.hue": "Hue",
  "text.integrated-camera": "Integrated camera",
  "text.italic": "Italic",
  "text.more": "More",
  "text.more-options": "More options",
  "text.mute": "Mute",
  "text.navigation-menu": "Navigation menu",
  "text.open-navigation": "Open navigation",
  "text.close-navigation": "Close navigation",
  "text.next": "Next",
  "text.navigationview": "NavigationView",
  "text.navigationview-description": "The NavigationView control provides a common vertical layout for top-level areas of your app via a collapsible navigation menu.",
  "sample.navigationview.default-header": "NavigationView with default PaneDisplayMode",
  "sample.navigationview.top-header": "NavigationView with PaneDisplayMode set to Top",
  "sample.navigationview.adaptive-header": "NavigationView that switches pane orientation based on window width",
  "sample.navigationview.tabs-header": "Tying selection and focus - Tabs",
  "sample.navigationview.data-binding-header": "Data binding",
  "sample.navigationview.footer-header": "NavigationView with Footer Menu Items",
  "sample.navigationview.hierarchical-header": "Hierarchical NavigationView",
  "sample.navigationview.api-header": "API in action",
  "sample.navigationview.default-description": "If you have five or more equally important navigation categories that should prominently appear on larger window widths, consider using a left navigation pane.",
  "sample.navigationview.top-description": "If you have equally important navigation categories that should be de-emphasized relative to the content of your app, consider using a top navigation pane.",
  "sample.navigationview.adaptive-description": "If you have equally important navigation categories and limited app content space, consider using a top navigation pane on larger window widths and a minimal left navigation pane on smaller window widths.",
  "sample.navigationview.tabs-description": "For the tabs pattern, ensure that you unify selection and focus by setting the SelectionFollowsFocus property to Enabled. If using a Frame to swap out content, then navigating between items shouldn't be recorded into the Frame's navigation stack. Please see the C# in the sample below to understand how to do this.",
  "sample.navigationview.data-binding-description": "When data binding, use the MenuItemsSource property to bind to an observable collection of items, and do not set the MenuItems property. In addition, set the MenuItemTemplate property and use a NavigationViewItem as the data template. If you wish to bind to the header content as well, use data template selectors via the MenuItemTemplateSelector property.",
  "sample.navigationview.footer-description": "You can add clickable menu items to the footer of your NavigationView that participate in the same selection model as items in the main menu. In Top PaneDisplayMode, these items will appear aligned to the right of the NavigationView. In Left PaneDisplayMode, these items will appear aligned to the bottom of the NavigationView.",
  "sample.navigationview.hierarchy-description-1": "NavigationView supports hierarchy in Left, LeftCompact, and Top display modes.",
  "sample.navigationview.hierarchy-description-2": "In the example below, the \"Account\" tab navigates to its own page while \"Document options\" only opens its subtree of items. This is done by setting the SelectsOnInvoked property to false on the Document options NavigationView item.",
  "sample.navigationview.hierarchy-description-3": "In both Top and Left modes, clicking the arrows on NavigationViewItems will expand or collapse the subtree. Clicking or tapping elsewhere on the NavigationViewItem will also collapse or expand the subtree.",
  "sample.navigationview.hierarchy-description-4": "Switch between the three pane display modes on the right.",
  "sample.navigationview.header-text": "This is Header Text",
  "sample.navigationview.menu-item-1": "Menu Item1",
  "sample.navigationview.menu-item-2": "Menu Item2",
  "sample.navigationview.menu-item-3": "Menu Item3",
  "sample.navigationview.menu-item-4": "Menu Item4",
  "sample.navigationview.item-1": "Item1",
  "sample.navigationview.item-2": "Item2",
  "sample.navigationview.item-3": "Item3",
  "sample.navigationview.item-4": "Item4",
  "sample.navigationview.sample-page": "Sample Page {number}",
  "sample.navigationview.settings-page": "Sample Settings Page",
  "sample.navigationview.lorem-title": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "sample.navigationview.lorem-body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "sample.navigationview.category": "Category {number}",
  "sample.navigationview.category-tooltip": "This is category {number}",
  "sample.navigationview.browse": "Browse",
  "sample.navigationview.track-order": "Track an Order",
  "sample.navigationview.order-history": "Order History",
  "sample.navigationview.account": "Account",
  "sample.navigationview.your-cart": "Your Cart",
  "sample.navigationview.help": "Help",
  "sample.navigationview.pane-position": "Pane position:",
  "sample.navigationview.pane-position-property": "PanePosition:",
  "sample.navigationview.left-mode": "Left mode",
  "sample.navigationview.top-mode": "Top mode",
  "sample.navigationview.left-compact-mode": "LeftCompact mode",
  "sample.navigationview.home": "Home",
  "sample.navigationview.mail": "Mail",
  "sample.navigationview.calendar": "Calendar",
  "sample.navigationview.document-options": "Document options",
  "sample.navigationview.create-new": "Create new",
  "sample.navigationview.upload-file": "Upload file",
  "sample.navigationview.settings-visible": "Settings item visible",
  "sample.navigationview.back-visible": "Back button visible",
  "sample.navigationview.back-enabled": "Back button enabled",
  "sample.navigationview.autosuggest-visible": "AutoSuggestBox visible",
  "sample.navigationview.header-label": "Header:",
  "sample.navigationview.header-value": "Header",
  "sample.navigationview.always-show-header": "Always show header",
  "sample.navigationview.pane-title-label": "PaneTitle:",
  "sample.navigationview.pane-title-value": "Pane Title",
  "sample.navigationview.pane-custom-visible": "PaneCustomContent visible",
  "sample.navigationview.pane-footer-visible": "PaneFooter visible",
  "sample.navigationview.left": "Left",
  "sample.navigationview.top": "Top",
  "sample.navigationview.keyboard-selection-follows-focus": "Keyboard SelectionFollowsFocus",
  "sample.navigationview.suppress-menu-item-2": "Selection of Menu Item2 suppressed",
  "sample.navigationview.actions": "Actions",
  "sample.navigationview.more-info": "More info",
  "sample.navigationview.search": "Search",
  "sample.navigationview.download": "Download",
  "sample.navigationview.favorite": "Favorite",
  "sample.navigationview.change-theme": "Change theme",
  "sample.navigationview.add-favorite": "Add to favorites",
  "sample.navigationview.remove-favorite": "Remove from favorites",
  "text.numbering": "Numbering",
  "text.off": "Off",
  "text.on": "On",
  "sample.opacity": "Opacity",
  "text.paste": "Paste",
  "text.pause": "Pause",
  "text.play": "Play",
  "text.previous": "Previous",
  "text.r": "R",
  "text.redo": "Redo",
  "text.requesting-camera-permission": "Requesting camera permission...",
  "text.reveal-password": "Reveal password",
  "text.scroll-left": "Scroll left",
  "text.scroll-right": "Scroll right",
  "text.search": "Search",
  "text.select": "Select...",
  "text.select-all": "Select all",
  "text.settings": "Settings",
  "text.source-code": "Source code",
  "text.saturation": "Saturation",
  "text.submit-query": "Submit query",
  "text.switch-to-zoomed-out-view": "Switch to zoomed out view",
  "text.cancel": "Cancel",
  "text.unable-to-start-the-camera": "Unable to start the camera.",
  "text.underline": "Underline",
  "text.undo": "Undo",
  "text.unmute": "Unmute",
  "text.value": "Value",
  "text.volume": "Volume",
  "text.vue": "Vue",
  "text.xaml": "XAML",
  "control.infobadge.value": "{value} notifications",
  "control.infobadge.icon": "Notification",
  "control.infobadge.dot": "New notification",
  "control.infobar.close-button-name": "Close",
  "control.infobar.close-button-tooltip": "Close"
};
