export default {
  "app.shortTitle": "VoiceCraft",
  "app.title": "VoiceCraft",
  "app.version": "1.0.0",
  "app.author": "VoiceCraft",
  "text.app-name": "VoiceCraft",
  "text.app-description": "AI 驱动的文字转语音平台，基于微软 Edge TTS。",
  "text.tts": "文字转语音",
  "text.input-text": "输入文本",
  "text.input-placeholder": "请输入要转换为语音的文本内容，支持中文、英文、数字等...",
  "text.upload-txt": "上传 txt 文件",
  "text.voice": "语音选择",
  "text.speed": "语速调节",
  "text.pitch": "音调高低",
  "text.style": "语音风格",
  "text.generate": "开始生成语音",
  "text.generating": "生成中...",
  "text.loading": "正在生成语音，请稍候...",
  "text.download": "下载音频文件",
  "text.error-empty": "请输入要转换的文本内容",
  "text.upload-hint": "支持txt格式，最大500KB",
  "text.tab-text": "手动输入",
  "text.tab-file": "上传文件"
};
